### Site Settings ###
title               : K.N Anantha nandanan
description         : >-
                      I don't work hard, I work smart. <br> <br> Backend Developer/Networking and Analysis <br> <a href = "https://www.amrita.edu/"> Student at Amrita Vishwa Vidyapeetham</a> <br>  <a href="https://amfoss.in/" title = "amFOSS"> Member at amFOSS</a> <br>
baseurl             : ""                     # Change to empty quotes if you are hosting your site at <your-username>.github.io directly
repository          : ananthanandanan/ananthanandanan.github.io     # Change to <your-username>/<your-username>.github.io (or remove it if you don't need remote projects)
remote_theme        : YoussefRaafatNasry/portfolYOU


### Plugins ###
plugins:
  - jemoji


### Navbar Settings ###
nav_exclude:                                            # The following paths are excluded from navbar
  - pages/tags.html
  - pages/404.html
  - pages/index.md
  - documentation/partials/**                           # For Documentation Only


### Author Info ###
author:
  name              : K N Anantha nandanan
  image             : static/me.jpg
#  behance           : your_username
# dribbble          : your_username
  email             : ananthanandanan@gmail.com
#  facebook          : your_username
  github            : ananthanandanan
  gitlab            : ananthan_2k
  instagram         : ananthan2k
# kaggle            : your_username
  linkedin          : de-blank
#  medium            : your_username
# soundcloud        : your_username
  spotify           : Ananthan2k
# stackoverflow     : your_user_id
# tumblr            : your_username.tumblr.com
# twitch            : your_username
  twitter           : Ananthan2k
# vimeo             : your_username
# youtube           : your_channel_name
# keybase           : your_username


### Posts ###
permalink: /blog/:title


### Collections ###
collections:
  projects:
    output: true
    permalink: /projects/:name
  

### Disqus ###
disqus:
  shortname: de-blank                  # Your website Shortname on disqus


### Analytics ###
analytics:
  enabled: false                                        # Set true to enable analytics
  google:
    tracking_id: your-google-tracking-id


### Defaults for collections ###
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "posts"
    values:
      comments: true                                   # Set to true to enable disqus comments

### Exclude from processing ###
exclude:
  - README.md
  - CONTRIBUTING.md
  - LICENSE
  - "*.log"
